version: "3.3"

services:
  api:
    image: dodoworkshop/widoo-back:develop
    environment:
      DB_HOST: db
      DB_NAME: widoo
      DB_USER: widoo
      DB_PASSWORD: widoo
      LOG_REQUESTS: "true"
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: mariadb:latest
    restart: on-failure
    environment:
      MARIADB_DATABASE: widoo
      MARIADB_USER: widoo
      MARIADB_PASSWORD: widoo
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql

volumes:
  database: